routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::resource('comments', 'CommentController');
    Route::resource('clones', 'CloneController');
    Route::resource('courses', 'CourseController');
    Route::resource('chapters', 'ChapterController');
    Route::resource('lessons', 'LessonController');
//    Route::get('section/{id}/', 'LessonController@list')->name('section.list');
//    Route::resource('subjects', 'SubjectController');
    Route::delete('subjects/{id}', 'SubjectController@destroy')->name('subjects.destroy');
    Route::get('chapter-list/{course_id}/{subject_id}', 'SubjectController@listchap')->name('subject.list');
    Route::get('subject-list/{id}', 'SubjectController@list')->name('subjects.list');
    Route::resource('admins', 'AdminController');
    Route::resource('sections', 'SectionController');
    Route::resource('chapters', 'ChapterController');
    Route::get('list-sections/{id_lesson}', 'SectionController@findLesson')->name('lessons.list');
    Route::get('list-quiz/{id_lesson}', 'SectionController@quiz')->name('lessons.quiz');
    Route::post('download-quiz/{id_lesson}', 'SectionController@download')->name('section.post');
    Route::get('download-quiz/{id_lesson}', 'SectionController@download')->name('section.download');
    Route::get('li-thuyet/{id_lesson}', 'ChapterController@lithuyet')->name('lessons.lithuyet');
});

app/Http/Controllers/Admin/SectionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entities\Admin;
use App\Entities\Quiz;
use App\Entities\Section;
use App\Http\Controllers\Controller;
use App\Repositories\SectionRepositoryEloquent;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Spatie\Browsershot\Browsershot;
use VerumConsilium\Browsershot\Facades\PDF;

class SectionController extends Controller
{
    protected $page;

    public function __construct(SectionRepositoryEloquent $page)
    {
        $this->page = $page;
    }

    public function create()
    {
        return view('comment.add');
    }

    public function findLesson(Request $request, $id)
    {
        if ($request->has('type')) {
            $data['sections'] = Section::where('lesson_id', (int)$id)->where('type', (int)$request->type)->get();
        } else {
            $data['sections'] = Section::where('lesson_id', (int)$id)->get();
        }

//        dd($data);
        return view('section.view')->with($data);
    }

    public function quiz($id)
    {
        Session::forget('exam');
        $collection = collect(Quiz::where('lesson_id', (int)$id)->get());
        $shuffled = $collection->shuffle();
        $shuffled->all();
        Session::put('exam', $shuffled);
        $data['quizzes'] = $shuffled;
        $data['id_lesson'] = $id;
        return view('section.quiz')->with($data);
    }

    public function download(Request $request, $id)
    {
//        if ($request->ajax()) {
//            $pdf = App::make('dompdf.wrapper');
////            dd($request->all());
//            $pdf->loadHTML($request->html);
//            return $pdf->save('abc234123.pdf');
////            Session::put('exam', $request->html);
////            dd(Session::get('exam'));
//        } else {
//           Session::get('exam');
//            $pdf = App::make('dompdf.wrapper');
//            $pdf->loadHTML(Session::get('exam'));
//            return $pdf->stream();
//        }
//        dd(1);
        $exam = Session::get('exam');
        $data['quizzes'] = $exam;
        $data['id_lesson'] = $id;

//        return PDF::loadHtml('<h1>Awesome PDF</h1>')
//            ->setNodeBinary('C:\Windows\System32\cmd.exe node')
//            ->storeAs('pdfs/', 'google.pdf');
        return Browsershot::url('https://www.google.com')
            ->setNodeBinary('C:\Windows\System32\cmd.exe node')
            ->noSandbox()->format('a4')->save('C:\xampp\htdocs\db-mongo\public\demo.pdf');
//        loadHtml('<h1>Awesome PDF</h1>')
//          ->setNodeBinary('C:\Windows\System32\cmd.exe node')
//            ->inline();
//        ChromePDF::loadView('section.quiz',$data)->inline();
//        ChromePDF::loadView('section.quiz', $data)->inline();
//            ->size('a4')
//            ->landscape()
//            ->download("invoice.pdf");

//        $pdfStoredPath = PDF::loadUrl('https://google.com')
//            ->setNodeBinary('C:/Program Files/nodejs/node.exe')
//            ->setNpmBinary('C:\Program Files\nodejs\npm.CMD')
//            ->inline();
//        $exam = Session::get('exam');
//        $data['quizzes'] = $exam;
//        $data['id_lesson'] = $id;
//        PDF::loadView('section.quiz',$data)->inline();
    }

    public function edit(Request $request, $id)
    {
        $data['section'] = Section::where('_id', $id)->first();
//        dd( $data['section']->content);
        return view('section.edit')->with($data);
    }

    public function update(Request $request, $id)
    {
        Admin::where('_id', $id)->update([
            'name' => $request->name,
        ]);
        return redirect()->route('comment.comments.index');
    }

    public function list($id)
    {
        $data['sections'] = Section::where('lesson_id', (int)$id)->get();
        return view('section.view')->with($data);
    }

    public function destroy($id)
    {
        $this->page->delete($id);
        return back();
    }
}

resources/views/section/add.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Form control: input</h2>
    <p>The form below contains two input elements; one of type text and one of type password:</p>
    <form action="{{route('admin.courses.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="usr">Admin:</label>
            <select name="admin_id" class="form-control" id="">
                @foreach($admins as $id=>$name)
                    <option value="{{$id}}">{{$name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="usr">Name:</label>
            <input type="text" class="form-control" name="name" id="usr">
        </div>
        <div class="form-group">
            <label for="usr">Mô tả:</label>
            <textarea class="form-control" id="" cols="30" name="description"
                      rows="10"></textarea>
        </div>
        <button class="btn btn-success" type="submit">Thêm mới</button>
    </form>
</div>

</body>
</html>

resources/views/section/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {{--<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>--}}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"></script>

</head>
<body>
{{--<div id="MathJax_Message"></div>--}}
<div class="container">
    <h2>{{$section->chapter->name}}</h2>
    <h3>{{@$section->lesson->name}}</h3>
    <h4 class="text-center">{{$section->name}}</h4>
    Câu hỏi :
    <br>
    {!! $section->question !!}
    Câu trả lời :
    <br>
    {!! $section->answer !!}

</div>

</body>
</html>

resources/views/section/lithuyet.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {{--<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>--}}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"></script>

</head>
<body>
{{--<div id="MathJax_Message"></div>--}}
<div class="container">
    <h2>{{$section->chapter->name}}</h2>
    <h3>{{@$section->lesson->name}}</h3>
    <h4 class="text-center">{{$section->name}}</h4>
    <br>
    {!! $section->content !!}

</div>

</body>
</html>

resources/views/section/quiz.blade.php
<h1>ádasuydkla</h1>{{--<!DOCTYPE html>--}}
{{--<html lang="vi">--}}
{{--<head>--}}
    {{--<title>Bootstrap Example</title>--}}
    {{--<meta charset="UTF-8">--}}
    {{--<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>--}}
    {{--<link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">--}}

    {{--<script media="all" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>--}}
    {{--<script media="all" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>--}}
    {{--<script media="all" type="text/javascript"--}}
            {{--src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"></script>--}}
    {{--<script>--}}
        {{--$(document).on('click', '#abc', function (e) {--}}
            {{--alert(2)--}}
            {{--e.preventDefault()--}}
            {{--$.ajax({--}}
                {{--type: 'POST',--}}
                {{--url: '{!! route('admin.section.post',['id_lesson'=>$id_lesson]) !!}',--}}
                {{--data: {--}}
                    {{--'_token': '{{@csrf_token()}}',--}}
                    {{--html: $('body').html()--}}
                {{--},--}}
                {{--error: function (error) {--}}
                    {{--console.log(error)--}}
                {{--},--}}
                {{--success: function (data) {--}}
                    {{--console.log(data)--}}
                {{--},--}}
            {{--});--}}
        {{--})--}}
    {{--</script>--}}
{{--</head>--}}
{{--<body>--}}

{{--<link rel="stylesheet" media="all" href="{{asset('css/style.css')}}">--}}
{{--<h1 id="abc"><a target="_blank" href="{{route('admin.section.download',['id_lesson'=>$id_lesson])}}"--}}
    {{-->Tai file</a></h1>--}}
{{--<div class="container">--}}
    {{--@foreach($quizzes as $key=>$quiz)--}}
        {{--<h4 class="text-left">Câu : {{$key+1}}{!! $quiz->question !!}</h4>--}}
        {{--<div class="row">--}}
            {{--@foreach($quiz->answer as $answer)--}}
                {{--<div class="col-md-3">--}}
                    {{--{!! $answer->content !!}--}}
                    {{--<input type="radio" name="answer-{{$key}}" value="{{$answer->_id}}">--}}
                {{--</div>--}}
            {{--@endforeach--}}
        {{--</div>--}}
    {{--@endforeach--}}
{{--</div>--}}

{{--</body>--}}
{{--</html>--}}

resources/views/section/view.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Basic Table</h2>
    <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
    <a href="{{route('admin.admins.create')}}" class="btn btn-success">Thêm</a>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>

            <th>Ngày tạo</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($sections as $section)
            <tr>
                <td>{{$section->_id}}</td>
                <td>{{$section->name}}</td>
                <td>{{$section->created_at}}</td>
                <td>
                    <a href="{{route('admin.sections.edit',$section->_id)}}">Sửa</a>
                    {{--<a href="{{route('admin.sections.show',$section->_id)}}">xem</a>--}}
                    <form action="{{route('admin.sections.destroy',$section->_id)}}" method="post">
                        @csrf
                        @method('delete')
                        {{--<button type="submit">Xóa</button>--}}
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

</body>
</html>