routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::resource('comments', 'CommentController');
    Route::resource('clones', 'CloneController');
    Route::resource('courses', 'CourseController');
    Route::resource('chapters', 'ChapterController');
    Route::resource('lessons', 'LessonController');
//    Route::get('section/{id}/', 'LessonController@list')->name('section.list');
//    Route::resource('subjects', 'SubjectController');
    Route::delete('subjects/{id}', 'SubjectController@destroy')->name('subjects.destroy');
    Route::get('chapter-list/{course_id}/{subject_id}', 'SubjectController@listchap')->name('subject.list');
    Route::get('subject-list/{id}', 'SubjectController@list')->name('subjects.list');
    Route::resource('admins', 'AdminController');
    Route::resource('sections', 'SectionController');
    Route::resource('chapters', 'ChapterController');
    Route::get('list-sections/{id_lesson}', 'SectionController@findLesson')->name('lessons.list');
    Route::get('list-quiz/{id_lesson}', 'SectionController@quiz')->name('lessons.quiz');
    Route::post('download-quiz/{id_lesson}', 'SectionController@download')->name('section.post');
    Route::get('download-quiz/{id_lesson}', 'SectionController@download')->name('section.download');
    Route::get('li-thuyet/{id_lesson}', 'ChapterController@lithuyet')->name('lessons.lithuyet');
});

app/Http/Controllers/Admin/ChapterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entities\Admin;
use App\Entities\Lesson;
use App\Entities\Section;
use App\Http\Controllers\Controller;
use App\Repositories\ChapterRepositoryEloquent;
use Illuminate\Http\Request;

class ChapterController extends Controller
{
    protected $page;

    public function __construct(ChapterRepositoryEloquent $page)
    {
        $this->page = $page;
    }

    public function create()
    {
        return view('comment.add');
    }

    public function findLesson($id)
    {
        $data['sections'] = Section::where('lesson_id', (int)$id)->get();
//        dd($data);
        return view('section.view')->with($data);
    }

    /*    public function index(Request $request)
        {
    //        dd(Admin::find(2)->comments);
            $data['admins'] = Admin::pluck('name', '_id')->toArray();
            $data['comments'] = Comment::whereNull('comment_id')->get();
    //        dd($data);
            return view('comment.view')->with($data);
        }

        public function store(Request $request)
        {
            $data = array_merge($request->only('content'), [
                'admin_id' => (int)$request->admin_id,
                'comment_id' => $request->comment_id,
            ]);
            Comment::create($data);
            return redirect()->route('admin.comments.index');
        }*/

    public function edit(Request $request, $id)
    {
        $data['lessons'] = Lesson::where('chapter_id', (int)$id)->get();
        $data['sections'] = Section::where('chapter_id', (int)$id)->whereNull('lesson_id')->get();
        return view('chapter.edit')->with($data);
    }

    public function lithuyet($lesson_id)
    {
        $data['section'] = Section::where('lesson_id', (int)$lesson_id)->where('type', 3)->first();
        return view('section.lithuyet')->with($data);
    }

    public function show(Request $request, $id)
    {
        $data['courses'] = Admin::where('_id', $id)->first()->courses;
        return view('comment.list')->with($data);
    }

    public function destroy($id)
    {
        $this->page->delete($id);
        return back();
    }
}

resources/views/chapter/add.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Form control: input</h2>
    <p>The form below contains two input elements; one of type text and one of type password:</p>
    <form action="{{route('admin.courses.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="usr">Admin:</label>
            <select name="admin_id" class="form-control" id="">
                @foreach($admins as $id=>$name)
                    <option value="{{$id}}">{{$name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="usr">Name:</label>
            <input type="text" class="form-control" name="name" id="usr">
        </div>
        <div class="form-group">
            <label for="usr">Mô tả:</label>
            <textarea class="form-control" id="" cols="30" name="description"
                      rows="10"></textarea>
        </div>
        <button class="btn btn-success" type="submit">Thêm mới</button>
    </form>
</div>

</body>
</html>

resources/views/chapter/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Basic Table</h2>
    <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
    <a href="{{route('admin.admins.create')}}" class="btn btn-success">Thêm</a>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>

            <th>SGK</th>
            <th>SBT</th>
            <th>TRNG</th>
            <th>Ngày tạo</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($lessons as $lesson)
            <tr>
                <td>{{$lesson->_id}}</td>
                <td>{{$lesson->name}}</td>
                <td>{!! $lesson->sgk !!}</td>
                <td>{!! $lesson->sbt !!}</td>
                <td>{!! $lesson->tracnghiem !!}</td>
                <td>{{$lesson->created_at}}</td>
                <td>
                    <a href="{{route('admin.lessons.list',$lesson->_id)}}">Câu hỏi</a>
                    {!! $lesson->lithuyet !!}
                    {{--<a href="{{route('admin.lessons.lithuyet',$lesson->_id)}}">Xem lí thuyết</a>--}}
                    <form action="{{route('admin.lessons.destroy',$lesson->_id)}}" method="post">
                        @csrf
                        @method('delete')
                        {{--<button type="submit">Xóa</button>--}}
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{--<table class="table">--}}
    {{--<thead>--}}
    {{--<tr>--}}
    {{--<th>ID</th>--}}
    {{--<th>Name</th>--}}

    {{--<th>Ngày tạo</th>--}}
    {{--<th>Action</th>--}}
    {{--</tr>--}}
    {{--</thead>--}}
    {{--<tbody>--}}
    {{--@foreach($sections as $section)--}}
    {{--<tr>--}}
    {{--<td>{{$section->_id}}</td>--}}
    {{--<td>{{$section->name}}</td>--}}
    {{--<td>{{$section->created_at}}</td>--}}
    {{--<td>--}}
    {{--<a href="{{route('admin.sections.edit',$section->_id)}}">Sửa</a>--}}
    {{--<form action="{{route('admin.sections.destroy',$section->_id)}}" method="post">--}}
    {{--@csrf--}}
    {{--@method('delete')--}}
    {{--<button type="submit">Xóa</button>--}}
    {{--</form>--}}
    {{--</td>--}}
    {{--</tr>--}}
    {{--@endforeach--}}
    {{--</tbody>--}}
    {{--</table>--}}
</div>

</body>
</html>

resources/views/chapter/view.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Basic Table</h2>
    <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
    <a href="{{route('admin.admins.create')}}" class="btn btn-success">Thêm</a>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>

            <th>Ngày tạo</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($sections as $section)
            <tr>
                <td>{{$section->_id}}</td>
                <td>{{$section->name}}</td>
                <td>{{$section->created_at}}</td>
                <td>
                    <a href="{{route('admin.sections.edit',$section->_id)}}">Sửa</a>
                    <a href="{{route('admin.sections.show',$section->_id)}}">xem</a>
                    <form action="{{route('admin.sections.destroy',$section->_id)}}" method="post">
                        @csrf
                        @method('delete')
                        {{--<button type="submit">Xóa</button>--}}
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

</body>
</html>