routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::resource('comments', 'CommentController');
    Route::resource('clones', 'CloneController');
    Route::resource('courses', 'CourseController');
    Route::resource('chapters', 'ChapterController');
    Route::resource('lessons', 'LessonController');
//    Route::get('section/{id}/', 'LessonController@list')->name('section.list');
//    Route::resource('subjects', 'SubjectController');
    Route::delete('subjects/{id}', 'SubjectController@destroy')->name('subjects.destroy');
    Route::get('chapter-list/{course_id}/{subject_id}', 'SubjectController@listchap')->name('subject.list');
    Route::get('subject-list/{id}', 'SubjectController@list')->name('subjects.list');
    Route::resource('admins', 'AdminController');
    Route::resource('sections', 'SectionController');
    Route::resource('chapters', 'ChapterController');
    Route::get('list-sections/{id_lesson}', 'SectionController@findLesson')->name('lessons.list');
    Route::get('list-quiz/{id_lesson}', 'SectionController@quiz')->name('lessons.quiz');
    Route::post('download-quiz/{id_lesson}', 'SectionController@download')->name('section.post');
    Route::get('download-quiz/{id_lesson}', 'SectionController@download')->name('section.download');
    Route::get('li-thuyet/{id_lesson}', 'ChapterController@lithuyet')->name('lessons.lithuyet');
});

resources/views/admin/add.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Form control: input</h2>
    <p>The form below contains two input elements; one of type text and one of type password:</p>
    <form action="{{route('admin.admins.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="usr">Name:</label>
            <input type="text" class="form-control"  name="name" id="usr">
        </div>
        <button class="btn btn-success" type="submit">Thêm mới</button>
    </form>
</div>

</body>
</html>

resources/views/admin/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Form control: input</h2>
    <p>The form below contains two input elements; one of type text and one of type password:</p>
    <form action="{{route('admin.admins.update',$admin->id)}}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="usr">Name:</label>
            <input type="text" class="form-control" value="{{$admin->name}}" name="name" id="usr">
        </div>
        <button class="btn btn-success" type="submit">Cập nhật</button>
    </form>
</div>

</body>
</html>

resources/views/admin/list.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Basic Table</h2>
    <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
    <a href="{{route('admin.courses.create')}}" class="btn btn-success">Thêm</a>
    <a href="{{route('admin.admins.index')}}" class="btn btn-success">Admin</a>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Slug</th>
            <th>Mô tả</th>
            <th>Ngày tạo</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($courses as $course)
            <tr>
                <td>{{$course->_id}}</td>
                <td>{{$course->name}}</td>
                <td>{{$course->slug}}</td>
                <td>{{$course->description}}</td>
                <td>{{$course->created_at}}</td>
                <td>
                    <a href="{{route('admin.courses.edit',$course->_id)}}">Sửa</a>
                    <form action="{{route('admin.courses.destroy',$course->_id)}}" method="post">
                        @csrf
                        @method('delete')
                        {{--<button type="submit">Xóa</button>--}}
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

</body>
</html>

resources/views/admin/view.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Basic Table</h2>
    <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
    <a href="{{route('admin.admins.create')}}" class="btn btn-success">Thêm</a>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>

            <th>Ngày tạo</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($admins as $course)
            <tr>
                <td>{{$course->_id}}</td>
                <td>{{$course->name}}</td>
                <td>{{$course->created_at}}</td>
                <td>
                    <a href="{{route('admin.admins.edit',$course->_id)}}">Sửa</a>
                    <a href="{{route('admin.admins.show',$course->_id)}}">xem</a>
                    <form action="{{route('admin.admins.destroy',$course->_id)}}" method="post">
                        @csrf
                        @method('delete')
                        {{--<button type="submit">Xóa</button>--}}
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

</body>
</html>