routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::resource('comments', 'CommentController');
    Route::resource('clones', 'CloneController');
    Route::resource('courses', 'CourseController');
    Route::resource('chapters', 'ChapterController');
    Route::resource('lessons', 'LessonController');
//    Route::get('section/{id}/', 'LessonController@list')->name('section.list');
//    Route::resource('subjects', 'SubjectController');
    Route::delete('subjects/{id}', 'SubjectController@destroy')->name('subjects.destroy');
    Route::get('chapter-list/{course_id}/{subject_id}', 'SubjectController@listchap')->name('subject.list');
    Route::get('subject-list/{id}', 'SubjectController@list')->name('subjects.list');
    Route::resource('admins', 'AdminController');
    Route::resource('sections', 'SectionController');
    Route::resource('chapters', 'ChapterController');
    Route::get('list-sections/{id_lesson}', 'SectionController@findLesson')->name('lessons.list');
    Route::get('list-quiz/{id_lesson}', 'SectionController@quiz')->name('lessons.quiz');
    Route::post('download-quiz/{id_lesson}', 'SectionController@download')->name('section.post');
    Route::get('download-quiz/{id_lesson}', 'SectionController@download')->name('section.download');
    Route::get('li-thuyet/{id_lesson}', 'ChapterController@lithuyet')->name('lessons.lithuyet');
});

app/Http/Controllers/Admin/CourseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entities\Admin;
use App\Entities\Course;
use App\Entities\Subject;
use App\Repositories\CourseRepositoryEloquent;
use Illuminate\Http\Request;

class CourseController extends BaseController
{
    protected $page;

    public function __construct(CourseRepositoryEloquent $page)
    {
        $this->page = $page;
    }

    public function create()
    {
        $data['admins'] = Admin::pluck('name', 'id')->toArray();
        return view('course.add')->with($data);
    }

    public function index(Request $request)
    {
        $data['courses'] = Course::all();
        return view('course.view')->with($data);
    }

    public function store(Request $request)
    {
        Course::create([
            'name' => $request->name,
            'slug' => str_slug($request->name, '-'),
            'description' => $request->description,
            'admin_id' => (int)$request->admin_id,
        ]);
        return redirect()->route('admin.courses.index');
    }

    public function edit(Request $request, $id)
    {
        $data['admins'] = Admin::pluck('name', '_id')->toArray();
        $data['course'] = Course::where('_id', $id)->first();
        return view('course.edit')->with($data);
    }

    public function list(Request $request, $id)
    {
        $data['subjects'] = Subject::where('course_id', $id)->get();
        return view('course.list')->with($data);
    }

    public function update(Request $request, $id)
    {
        Course::where('_id', $id)->update([
            'name' => $request->name,
            'slug' => str_slug($request->name, '-'),
            'description' => $request->description,
            'admin_id' => (int)$request->admin_id,
        ]);
        return redirect()->route('admin.courses.index');
    }

    public function destroy($id)
    {
        $this->page->delete($id);
        return redirect()->route('admin.courses.index');
    }
}

resources/views/course/add.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Form control: input</h2>
    <p>The form below contains two input elements; one of type text and one of type password:</p>
    <form action="{{route('admin.courses.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="usr">Admin:</label>
            <select name="admin_id" class="form-control" id="">
                @foreach($admins as $id=>$name)
                    <option value="{{$id}}">{{$name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="usr">Name:</label>
            <input type="text" class="form-control" name="name" id="usr">
        </div>
        <div class="form-group">
            <label for="usr">Mô tả:</label>
            <textarea class="form-control" id="" cols="30" name="description"
                      rows="10"></textarea>
        </div>
        <button class="btn btn-success" type="submit">Thêm mới</button>
    </form>
</div>

</body>
</html>

resources/views/course/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Form control: input</h2>
    <p>The form below contains two input elements; one of type text and one of type password:</p>
    <form action="{{route('admin.courses.update',$course->_id)}}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="usr">Admin:</label>
            <select name="admin_id" class="form-control" id="">
                @foreach($admins as $id=>$name)
                    <option value="{{$id}}">{{$name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="usr">Name:</label>
            <input type="text" class="form-control" value="{{$course->name}}" name="name" id="usr">
        </div>
        <div class="form-group">
            <label for="usr">Mô tả:</label>
            <textarea class="form-control" id="" cols="30" name="description"
                      rows="10">{{$course->description}}</textarea>
        </div>
        <button class="btn btn-success" type="submit">Cập nhật</button>
    </form>
</div>

</body>
</html>

resources/views/course/list.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Basic Table</h2>
    <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
    <a href="{{route('admin.courses.create')}}" class="btn btn-success">Thêm</a>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Name</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($subjects as $subject)
            <tr>
                <td>{{$subject->_id}}</td>
                <td>{{$subject->name}} </td>
                <td>
                    <a href="{{route('admin.subject.list',['subject_id'=>$subject->_id,'course_id'=>$course->_id])}}">Sửa</a>
                    {{--<a href="{{route('admin.subjects.list',$subject->_id)}}">Xem</a>--}}
                    <form action="{{route('admin.subjects.destroy',$subject->_id)}}" method="post">
                        @csrf
                        @method('delete')
                        {{--<button type="submit">Xóa</button>--}}
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

</body>
</html>

resources/views/course/view.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Basic Table</h2>
    <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
    <a href="{{route('admin.admins.create')}}" class="btn btn-success">Thêm</a>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>

            <th>Ngày tạo</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($courses as $course)
            <tr>
                <td>{{$course->_id}}</td>
                <td>{{$course->name}}</td>
                <td>{{$course->created_at}}</td>
                <td>
                    <a href="{{route('admin.courses.edit',$course->_id)}}">Sửa</a>
                    <a href="{{route('admin.subjects.list',$course->_id)}}">xem</a>
                    <form action="{{route('admin.courses.destroy',$course->_id)}}" method="post">
                        @csrf
                        @method('delete')
                        {{--<button type="submit">Xóa</button>--}}
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

</body>
</html>